Add LAPACK overloads for all variants of `pt.linalg.solve`
pymc-devs/pytensor pull request #1146
Opened 2024-12-31 07:20 UTC by jessegrabowski

## Description

Goal of this PR is to give numba mode full coverage of `scipy.linalg.solve` options. We currently only support `assume_a = "gen"`. If users select a different solver, they get incorrect results (see #422 ). This PR should fix that bug, plus add:

- [ ] support for `overwrite_a` in numba mode
- [ ] support for `overwrite_b` in numba mode
- [ ] support for `transposed` argument (all modes)
- [ ] `lu_factor` and `lu_solve` `Ops` (all modes)
- [ ] support for `assume_a = "sym"` and `assume_a = "pos"` in numba mode

So far I've implemented `assume_a = "gen"` using LU decomposition, which should offer a speedup compared to what we're doing now. Next I'll do the other two cases. 

We get the `lu_factor` and `lu_solve` Ops kind of "for free" because I'm adding overloads for `dgetrs` and `dgetrf`. We just have to write the Ops and do the JAX dispatch. JVP for `lu_factor` is [here](https://github.com/jax-ml/jax/blob/494c15733c5b600f64c3128978c143a82537a830/jax/_src/lax/linalg.py#L1557).  Help wanted. I might decide that these Ops are out of scope for this PR and open another one.

## Related Issue

- [ ] Closes #422

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [x] New feature / enhancement
- [x] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2025-01-05 05:09 UTC, jessegrabowski commented
This is pretty close. I just need some help with the destroy_map stuff on `Solve`. I guess this wasn't being before? The code is a bit hard to follow with all the subclassing.

2025-01-05 10:51 UTC, ricardoV94 requested changes
What do you mean we were not doing inplace? It was already implemented for the default backend for Solve and Cholesky: https://github.com/pymc-devs/pytensor/commit/ed6ca1620526b1f6c1a84f712127c062ec6d4e07#diff-f5e942a523e3c0402aa63824184c381f5a963867125a21f119e2dab97a110d95

Just not in Numba yet. You shouldn't change anything in how the Ops are created, it's handled by the inplace rewrites. You may need to explicitly trigger them in the numba tests (the default numba mode in `compare_py_and_numba` does not include them), but I am not sure that utility actually works with inplace stuff

2025-01-05 10:51 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +            overwrite_b=overwrite_b,
This has to be done via inplace rewrites, and should just be ignored like we do in other OPs: https://github.com/pymc-devs/pytensor/blob/54a2c6e06b4dc7fb3b91340cf139994667120cfb/pytensor/tensor/slinalg.py#L170-L172

2025-01-05 10:51 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +            overwrite_b=overwrite_b,
Same here

2025-01-05 10:51 UTC, ricardoV94 commented on tests/link/numba/test_slinalg.py
> +        overwrite_b=overwrite_b,
You're not testing if the inplacing is working explicitly in the numba backend. Do you want to? That would require checking the input was mutated, like we do here: https://github.com/pymc-devs/pytensor/blob/8cc489b1325995ccd375448c00b357cfb4211597/tests/tensor/test_blockwise.py#L596-L598

2025-01-05 10:58 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +            overwrite_b=overwrite_b,
Instead of saying it is ignored, we should say this is applied during rewrites when it is safe to destroy the input

2025-01-05 17:28 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> -            overwrite_b=self.overwrite_b,
This should stay (it's the perform)

2025-01-05 17:29 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Doesn't this require changes in the grads?

2025-01-06 01:01 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> -            overwrite_b=self.overwrite_b,
whoops

2025-01-06 01:06 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Yes, good catch

2025-02-10 09:41 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Something is wrong with gradients when `assume_a != 'gen'`. We agree with JAX, but not the numerical gradients for the gradient of A. According the to the numerical, it should become triangular. I think this is due to the numerical algorithm used? Not 100% sure how to proceed.

2025-02-10 10:45 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Is this related to the transposed?

2025-02-10 12:24 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
No, I worked out the gradients for the  transpose case. The story there is basically that we can add a rewrite for `solve(A.T, b) -> solve(A, b, transposed=True)`, and we never materialize the transpose, which can result in some savings. The only wrinkle is that in the gradients we need to do one extra transpose, because the gradient is with respect to A.T. BUT we still trade 2 transposes (one in the forward and one in the backward) for just one.

The problem here seems to be numeric. When you do `assume_a = "sym" | "pos"`, you trigger solvers that use special matrix decomposition (for example pos goes and goes cholesky solve). Numerically I think the numbers in the lower triangle of `A` won't be implicated at all, so the numerical gradient is comes back either wrong, or simplified in some way that we're not taking into account. But if that's the case, JAX doesn't take it into account either, because we agree with `jax.grad(jax.scipy.linalg.solve(A, b, assume_a).sum())`

2025-02-10 23:07 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
> and we never materialize the transpose, which can result in some savings.

Do note that transpose is always a view-only operation (no copy, just change strides). Although it may not be in some cases in Numba, #1111, which is lame / considerably a bug

2025-02-10 23:08 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Anyway for the gradient, just roll your own version of it, if the default doesn't do the job here with these degenerate values

2025-02-11 04:14 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
It's not clear to me if it's doing the wrong thing, or if there's something more subtle going on

2025-02-11 06:34 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Here's a gist showing the issue:

https://gist.github.com/jessegrabowski/4f30ebbde57758466f5b1579063ca6d0

2025-02-11 16:08 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        solve_args = {k: getattr(self, k) for k in self.__props__}
`self._props_dict()`

2025-02-11 16:09 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +            b_bar = solve_op(A, c_bar)
Do this as a rewrite?

2025-02-16 15:54 UTC, jessegrabowski commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Reverted the transpose stuff, though I think in the end it wasn't the reason my tests were failing. I think we can revisit the transpose argument as a rewrite in a future PR.

2025-02-16 20:06 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +            return [(n, n), (n, n), (n, n)]
If Elemwise doesn't do it yet, we should just like Blockwise and RandomVariable infer the shape from the signature

2025-02-16 20:44 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        LU(permute_l=permute_l, check_finite=check_finite, p_indices=p_indices)(a),
Not Blockwise by default?

2025-02-16 20:49 UTC, ricardoV94 commented on pytensor/link/numba/dispatch/slinalg.py
> +    @numba_basic.numba_njit(inline="always", cache=True)
We have a default handling of cache in the `numba_njit` already, why this explicit?

2025-02-16 20:50 UTC, ricardoV94 commented on pytensor/link/numba/dispatch/slinalg.py
> +    # TODO: Implement an LU_factor Op, then dispatch to this function in numba mode.
Outdated TODO?

2025-02-16 20:51 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +        self.transposed = transposed
Last commit seems to have the transposed stuff?

2025-02-16 20:53 UTC, ricardoV94 commented on tests/link/numba/test_slinalg.py
> +    )
hmm inplace=True shouldn't mutate the original inputs, I guess it may be doing it now?

2025-02-16 20:55 UTC, ricardoV94 commented on tests/tensor/test_slinalg.py
> +RTOL = 1e-8 if config.floatX.endswith("64") else 1e-4
I don't love these global ATOL/RTOL. Future developers may blindly use them thinking they are well thought defaults for any linalg operations?

2025-02-16 21:35 UTC, ricardoV94 commented
Missing dispatch for JAX (and possibly torch) for the LU Op?

2025-02-16 21:41 UTC, ricardoV94 commented on pytensor/tensor/slinalg.py
> +class LU(Op):
Missing gufunc_spec or whatever it's called, so that the Blockwise impl can avoid vectorize as scipy LU already works with batch dims?

2025-02-17 03:32 UTC, jessegrabowski commented on pytensor/link/numba/dispatch/slinalg.py
> +    @numba_basic.numba_njit(inline="always", cache=True)
I was playing around with settings and forgot to delete this. Good catch.

2025-02-17 03:32 UTC, jessegrabowski commented on pytensor/link/numba/dispatch/slinalg.py
> +    # TODO: Implement an LU_factor Op, then dispatch to this function in numba mode.
No, I still need lu_factor, not just lu.

2025-02-17 03:34 UTC, jessegrabowski commented on tests/link/numba/test_slinalg.py
> +    )
I might be able to remove those copies, it's being done inside `compare_numba_and_py`. I was trying a lot of different stuff to get this to work. Passing the fgraph with `pytensor.In(..., mutable=True)` inputs was breaking it.

2025-02-17 12:18 UTC, ricardoV94 approved these changes

2025-02-17 12:18 UTC, ricardoV94 commented
Also `test_solve_correctness` failing on float32

2025-02-17 14:26 UTC, merged