Handle incorrect BroadcastTo shape in C code
pymc-devs/pytensor pull request #175
Opened 2023-01-05 16:06 UTC by ricardoV94

Closes #152

2023-01-06 10:03 UTC, lucianopaz requested changes
Looks good @ricardoV94. I left three comments

2023-01-06 11:05 UTC, ricardoV94 commented on pytensor/tensor/extra_ops.py
> +            raise ValueError("Broadcast shape cannot be shorter than input shape")
Updated

2023-01-06 11:06 UTC, ricardoV94 commented on tests/tensor/test_extra_ops.py
> +
Added a parametrization to that test with invalid values. It seems to be behaving fine

2023-01-06 11:06 UTC, ricardoV94 commented on pytensor/tensor/extra_ops.py
> +                    %(fail)s
I move the creation of `iter` to after the check, even though the new test param did not show anything wrong

2023-01-06 11:09 UTC, ricardoV94 commented on tests/tensor/test_extra_ops.py
> +        assert np.mean(block_diffs) <= (0 + 1e-8)
This was failing with negative values, which should not be problematic

2023-01-06 21:09 UTC, lucianopaz approved these changes
LGTM @ricardoV94. I don't know what do make out of the performance regression. I doesn't seem related to this PR but I can't seem to find a way to get the detailed benchmark results from the cache or from this PR.

2023-01-06 21:30 UTC, ricardoV94 commented
The last cached benchmark might have been a CI fluke and this one looks bad in comparison?

Only the C scan test could possibly have been affected so I'll run it locally before and after the changes to see if it complains.

2023-01-07 06:55 UTC, lucianopaz commented
Looks like the performance regression problems are happening because the tests that use random are not being seeded, and different seeds can lead to very different run times

2023-01-08 08:29 UTC, ricardoV94 commented
I'll merge this and seed the benchmark in another PR. 

I am surprised that the speed of logsumexp is value dependent. Maybe the max is faster sometimes because of specific signs. Or log requires different number of terms depending on magnitude?

2023-01-08 13:25 UTC, merged