Raise NotScalarConstantError for homogenous non-scalar constants
pymc-devs/pytensor pull request #248
Opened 2023-03-14 12:27 UTC by shreyas3156

### Motivation for these changes
Closes #226 

### Implementation details

- Added a `get_scalar_constant()` method that raises NotScalarConstantError when non-scalar outputs are passed.
- Renamed the current `get_scalar_constant_value()` to `get_underlying_scalar_constant()`

### Checklist
+ [x] Explain motivation and implementation 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [x] Are the changes covered by tests and docstrings?
+ [x] Fill out the short summary sections 👇

## Major / Breaking Changes
- None

## Bugfixes
- Yes.

2023-03-17 19:57 UTC, ricardoV94 reviewed
Looks good. I think we just need to tweak the docstrings

2023-03-17 19:57 UTC, ricardoV94 commented on pytensor/tensor/basic.py
> +    Checks whether 'v' is a scalar based on 'ndim'
Can you tweak the docstrings, to be more direct about what it does?

2023-03-20 10:51 UTC, ricardoV94 requested changes
Some change requests, should be the last mile!

2023-03-20 10:51 UTC, ricardoV94 commented on pytensor/tensor/basic.py
> +def get_scalar_constant(v, elemwise=True, only_process_constants=False, max_recur=10):
We shouldn't change the name, even if it's a bit verbose.

```suggestion
def get_scalar_constant_value(v, elemwise=True, only_process_constants=False, max_recur=10):
```

2023-03-20 10:51 UTC, ricardoV94 commented on pytensor/tensor/basic.py
> +def get_underlying_scalar_constant(
To match the non-underlying 

```suggestion
def get_underlying_scalar_constant_value(
```

2023-03-22 09:11 UTC, shreyas3156 commented
@ricardoV94 It seems like the benchmark test is failing for a couple of tests in `tests/link/jax/test_elemwise.py`. Can you please help me understand it and if it is linked to any of the changes I made?

2023-03-22 18:03 UTC, ricardoV94 commented
That's probably just a fluke, nothing to worry about

2023-03-22 18:04 UTC, ricardoV94 approved these changes

2023-03-22 18:05 UTC, merged

2023-03-22 18:05 UTC, ricardoV94 commented
Thanks @shreyas3156