Moved logsumexp
pymc-devs/pytensor pull request #351
Opened 2023-06-20 07:35 UTC by KladeRe

### Motivation for these changes
This is a solution to issue #350

### Implementation details
Simply moved the function logsumexp from math.py to special.py and the functions that it needed.

### Checklist
+ [x] Explain motivation and implementation 👆
+ [x] Make sure that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html).
+ [x] Link relevant issues, preferably in [nice commit messages](https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html).
+ [x] The commits correspond to [_relevant logical changes_](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes). Note that if they don't, we will [rewrite/rebase/squash the git history](https://git-scm.com/book/en/v2/Git-Tools-Rewriting-History#_rewriting_history) before merging.
+ [x] Are the changes covered by tests and docstrings?
+ [ ] Fill out the short summary sections 👇

## Major / Breaking Changes
- ...

## New features
- Function was moved

## Bugfixes
- ...

## Documentation
- ...

## Maintenance
- ...

2023-06-20 07:38 UTC, ricardoV94 commented
Any tests and rewrites pertaining to `logsumexp` should also be moved from `.../math.py` to `.../special.py`

2023-06-20 08:26 UTC, KladeRe commented
I now moved local_logsumexp to special.py and test_logsumexp to tests/tensor/test_special.py. Are there any other tests or functions which need to be moved?

2023-06-20 16:55 UTC, KladeRe commented
Alright, everything related to logsumexp is now either in special.py or its tests.

2023-06-21 08:42 UTC, ricardoV94 requested changes

2023-06-21 08:42 UTC, ricardoV94 commented on pytensor/tensor/special.py
> +    """e^`a`"""
These shouldn't be here

2025-01-01 19:34 UTC, closed without merging