Add script to downstream PRs.
pymc-devs/pytensor pull request #39
Opened 2022-11-26 11:52 UTC by twiecki

2022-11-27 09:08 UTC, ricardoV94 approved these changes

2022-11-27 11:15 UTC, ferrine commented
I think a more descriptive or message is needed, very hard to figure out what the or was about

2022-11-27 11:30 UTC, ferrine requested changes
Needs a more descriptive pr title

2022-11-27 17:59 UTC, ferrine reviewed
I meant this informative title
```bash
curl https://api.github.com/repos/aesara-devs/aesara/pulls/1271 2>/dev/null | jq '.title'
"Implement multi-output Elemwise in Numba via guvectorize"
```

2022-11-27 18:09 UTC, ferrine commented on bin/downstream_pr.sh
> +
```suggestion
title=$(curl https://api.github.com/repos/aesara-devs/aesara/pulls/1271 2>/dev/null | jq '.title')
```

2022-11-27 18:09 UTC, ferrine commented on bin/downstream_pr.sh
> +gh pr create --repo pymc-devs/pytensor --title "Downstreaming Aesara PR $1" --body "Downstreaming https://github.com/aesara-devs/aesara/pull/$1. PR port done by downstream_pr.sh script."
```suggestion
gh pr create --repo pymc-devs/pytensor --title "Downstreaming Aesara PR $1: $title" --body "Downstreaming https://github.com/aesara-devs/aesara/pull/$1. PR port done by downstream_pr.sh script."
```

2022-11-28 06:28 UTC, ferrine approved these changes

2022-11-28 07:39 UTC, merged