Reconcile environment for development and docs building
pymc-devs/pytensor pull request #717
Opened 2024-04-15 13:53 UTC by HangenYuu

## Description

Updated the [environment.yml](https://github.com/pymc-devs/pytensor/blob/main/environment.yml) for developing and docs building locally.

## Related Issue

- [ ] Closes #716 
- [ ] Related to #687 

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [x] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-04-15 13:54 UTC, HangenYuu commented
Maybe not merge yet. Let me update the documentation first.

2024-04-15 15:28 UTC, twiecki approved these changes

2024-04-15 16:04 UTC, ricardoV94 commented
> Maybe not merge yet. Let me update the documentation first. I opened the PR first though.

You can click `Convert to a draft` button when a PR is not ready. That way there's no risk of premature merging. Anytime it's ready you click `Ready for review`

2024-04-16 12:37 UTC, HangenYuu commented
Okay I have also updated the documentation. The change should be good for merging.

2024-04-16 13:24 UTC, OriolAbril commented
Is anyone using the docgen.py script for something other than to generate the html build of the docs? I was just going over it and it basically calls sphinx with different defaults (such as default to building both html and pdf via latex instead of only building html).

If it isn't really being used (doc building and PR previews via readthedocs do not use it for example), it is probably best to remove and update the contributing guide a bit more to use the sphinx command directly instead of running docgen script

2024-04-16 13:25 UTC, OriolAbril requested changes

2024-04-16 13:25 UTC, OriolAbril commented on environment.yml
> +  - pip
It can be installed from conda forge too, no need to include pip and install from github

2024-04-16 13:52 UTC, HangenYuu commented
> Is anyone using the docgen.py script for something other than to generate the html build of the docs? I was just going over it and it basically calls sphinx with different defaults (such as default to building both html and pdf via latex instead of only building html).
> 
> If it isn't really being used (doc building and PR previews via readthedocs do not use it for example), it is probably best to remove and update the contributing guide a bit more to use the sphinx command directly instead of running docgen script

Agreed. Let me deal with this.

2024-04-16 14:18 UTC, OriolAbril commented on environment.yml
> +  - pip
The one in the doc folder should also be updated then. Link: https://anaconda.org/conda-forge/pymc-sphinx-theme

2024-04-21 05:23 UTC, HangenYuu commented
@OriolAbril 
- [x] Updated the dependency to install from `conda-forge` instead of `pip`.
- [x] Removed the script & updated the developer guide.

2024-04-21 08:44 UTC, OriolAbril approved these changes

2024-04-21 09:09 UTC, ricardoV94 commented
Thanks a ton @HangenYuu

2024-04-21 09:09 UTC, merged