Switched from miniconda-setup to micromamba-setup for mypy workflow
pymc-devs/pytensor pull request #781
Opened 2024-05-25 03:48 UTC by HangenYuu

## Description

Switch from using setup-miniconda to setup-micromamba in GitHub Actions for 3 current workflows

## Related Issue

- [ ] Closes #
- [ ] Related to #775 

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [x] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-05-25 03:51 UTC, HangenYuu commented
mypy.yml works as expected. Moving on to other workflows 👍.

2024-05-25 04:31 UTC, HangenYuu commented
This is this PR current output of the tests:
![image](https://github.com/pymc-devs/pytensor/assets/97870091/365b1105-9cac-43d4-830a-ec4fb8e66cce)

![image](https://github.com/pymc-devs/pytensor/assets/97870091/6283fdd9-d607-47f8-8e7d-9719c76cad31)
I wonder whether I should set this config flag directly in `test.yml`?

2024-05-29 08:09 UTC, ricardoV94 commented
CC @maresb @lucianopaz

2024-06-09 14:11 UTC, maresb commented
@HangenYuu, any reason you closed this? I went on vacation right after you created this. I was hoping that @lucianopaz would be able to look at the BLAS flags error.

2024-06-10 00:22 UTC, HangenYuu commented
I honestly did not know why too. I even deleted the branch. Let's me reopen it here.

2024-06-10 04:17 UTC, lucianopaz requested changes
@HangenYuu, it looks like your installation [isn't setting up the mamba command](https://github.com/pymc-devs/pytensor/actions/runs/9440568604/job/26000091232?pr=781#step:5:93). Instead of erroring out there, the jobs seems to continue and pip install pytensor. Without mkl, the jobs terminates because it does not find blas ldflags.

You should change all calls to `mamba` with `micromamba`. I suggested the few I could here, but there are more in the yml job files.

2024-06-10 04:17 UTC, lucianopaz commented on .github/workflows/test.yml
>            mamba install --yes -q "python~=${PYTHON_VERSION}=*_cpython" mkl numpy scipy pip mkl-service graphviz cython pytest coverage pytest-cov pytest-benchmark pytest-mock sympy
```suggestion
          micromamba install --yes -q "python~=${PYTHON_VERSION}=*_cpython" mkl numpy scipy pip mkl-service graphviz cython pytest coverage pytest-cov pytest-benchmark pytest-mock sympy
```

2024-06-10 04:17 UTC, lucianopaz commented on .github/workflows/test.yml
>            if [[ $INSTALL_NUMBA == "1" ]]; then mamba install --yes -q -c conda-forge "python~=${PYTHON_VERSION}=*_cpython" "numba>=0.57"; fi
```suggestion
          if [[ $INSTALL_NUMBA == "1" ]]; then micromamba install --yes -q -c conda-forge "python~=${PYTHON_VERSION}=*_cpython" "numba>=0.57"; fi
```

2024-06-10 04:17 UTC, lucianopaz commented on .github/workflows/test.yml
> +          mamba install --yes -q -c conda-forge "python~=${PYTHON_VERSION}=*_cpython" mkl numpy scipy pip mkl-service cython pytest "numba>=0.57" jax jaxlib pytest-benchmark
```suggestion
          micromamba install --yes -q -c conda-forge "python~=${PYTHON_VERSION}=*_cpython" mkl numpy scipy pip mkl-service cython pytest "numba>=0.57" jax jaxlib pytest-benchmark
```

2024-06-10 04:17 UTC, lucianopaz commented on .github/workflows/test.yml
> +          mamba list && pip freeze
```suggestion
          micromamba list && pip freeze
```

2024-06-11 02:39 UTC, HangenYuu commented
@lucianopaz I made the changes and the tests seem to be passed already. Honestly did not expect `micromamba` to be used instead of `mamba`, but that was just my assumption from using `miniconda`, which still uses `conda` to install package.

2024-06-11 11:10 UTC, twiecki approved these changes

2024-06-11 12:23 UTC, lucianopaz approved these changes
LGTM

2024-06-11 12:26 UTC, merged