Implemented Sort/Argsort Ops in PyTorch
pymc-devs/pytensor pull request #897
Opened 2024-07-07 19:38 UTC by twaclaw

## Description

* Implements `SortOp` in `PyTorch`
* Implements `ArgSortOp` in `PyTorch`
* :warning: passing `axis=None` throws an exception because `Reshape` is not yet implemented

## Related Issue

- [x] Related to #821 

## Checklist

- [x] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [x] Included tests that prove the fix is effective or that the new feature works
- [x] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [x] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-07-07 20:28 UTC, ricardoV94 commented
What happens with axis=None that introduces a reshape?

2024-07-07 20:45 UTC, twaclaw commented
> What happens with axis=None that introduces a reshape?

I think it is this [line](https://github.com/pymc-devs/pytensor/blob/4ea96b272247d3dc6f82987f1433d59cea94af1c/pytensor/tensor/sort.py#L148). But I should rather remove that test and don't test for `axis=None` for the time being.

2024-07-07 20:47 UTC, ricardoV94 commented
I see, you can mark it as xfail with pytest.mark.xfail

2024-07-08 12:41 UTC, ricardoV94 requested changes

2024-07-08 12:41 UTC, ricardoV94 commented on tests/link/pytorch/test_sort.py
>  @pytest.mark.parametrize("axis", [0, 1, None])
When only some of the parametrized conditions fail, you should use `pytest.param` to mark that specifically as xfailing. The others are working and shouldn't be marked. There are some examples in the tests somewhere

2024-07-10 07:56 UTC, ricardoV94 approved these changes

2024-07-10 07:56 UTC, merged