Update for m1
pymc-devs/pytensor pull request #941
Opened 2024-07-17 20:10 UTC by Ch0ronomato

## Description
My work machine is an M2 mac with the apple silicon. Not sure if this is a machine y'all are planning on supporting, but these were the changes I needed to make to environment.yaml to get off the ground.

## Related Issue

- [ ] Closes #
- [ ] Related to #

## Checklist

- [X] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [X] Maintenance
- [ ] Other (please specify):

2024-07-17 20:54 UTC, maresb commented
Ah, hmm, indeed this is pretty awkward. The proposed changes will break things for those not on Apple Silicon.

Ideally we should be doing something like depend on `libblas` and allow conda's pinning mechanism to install the right thing. I've messed around with it before, but never managed to get good results. I should probably poke at it some more.

2024-07-17 21:23 UTC, Ch0ronomato commented
I couldn't get anything either to be totally honest. It doesn't seem like it's a lost battle, but it gets me deving on an m1 for now - though I fully intend for it to be a bit of wasted pr. I did see there was some conda like `# [not osx]` type hints that might be relevant; though adding a `gen_environment.py` that does this resolution for us might be an okay fix

2024-07-17 22:28 UTC, twiecki requested changes
This would bake in accelerate instead of MKL, which we probably also don't want.

We figured out how to do this in the conda-forge package. https://github.com/conda-forge/pytensor-suite-feedstock/blob/main/recipe/meta.yaml Not sure it works here? 

Alternatively we could add a different environment.yml for ARM64.

2024-07-17 22:46 UTC, Ch0ronomato commented
@twiecki yea, an alternative env file makes sense as well

2024-07-18 07:20 UTC, maresb commented
Multiple env files are indeed a straightforward and simple workaround.

Those `# [python_expression]` things are called [preprocessing selectors](https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html#preprocess-selectors) and unfortunately only apply to the `meta.yaml` Conda recipe specification, not the `environment.yaml` spec.

2024-07-18 16:38 UTC, Ch0ronomato commented
Sounds great, I'll go ahead and edit this to be `environment_arm.yml`

2024-07-18 22:20 UTC, maresb commented
I'd recommend calling it `environment-osx-arm64.yaml`. (In addition to the `osx-arm64` platform there's also `linux-aarch64` where arm64 and aarch64 are synonymous, and `linux-aarch64` can be used for Docker containers on Apple Silicon.)

2024-07-22 07:06 UTC, maresb reviewed
This approach looks good for now. I think pixi would be able to handle this much more elegantly via features and multienvironments:

https://pixi.sh/latest/features/multi_environment/

But transitioning to pixi is a bit more involved, so let's get this merged for now.

2024-07-22 07:06 UTC, maresb commented on environment-osx-arm64.yml
> +  - python=3.10
Why not
```suggestion
  - python=>3.10
```
?

2024-07-22 09:56 UTC, twiecki approved these changes

2024-07-29 21:37 UTC, Ch0ronomato commented
Can we get this merged?

2024-07-29 21:59 UTC, maresb approved these changes
Thanks @Ch0ronomato! LGTM

2024-07-29 22:00 UTC, merged