Added rewrite for diag(block_diag)
pymc-devs/pytensor pull request #967
Opened 2024-08-10 10:32 UTC by tanish1729

## Description
Added rewrite for diag(block_diag(*sub_matrices)) -> concatenate(diag(sub_matrices)) 

## Related Issue

- [ ] Related to #573 

## Checklist

- [ ] Checked that [the pre-commit linting/style checks pass](https://docs.pymc.io/en/latest/contributing/python_style.html)
- [ ] Included tests that prove the fix is effective or that the new feature works
- [ ] Added necessary documentation (docstrings and/or example notebooks)
- [ ] If you are a pro: each commit corresponds to a [relevant logical change](https://wiki.openstack.org/wiki/GitCommitMessages#Structural_split_of_changes)

## Type of change

- [ ] New feature / enhancement
- [ ] Bug fix
- [ ] Documentation
- [ ] Maintenance
- [ ] Other (please specify):

2024-08-10 20:46 UTC, twiecki commented
You need to rebase.

2024-08-18 12:00 UTC, jessegrabowski requested changes

2024-08-18 12:00 UTC, jessegrabowski commented on pytensor/tensor/rewriting/linalg.py
> +@node_rewriter([det])
Will the rewrite be applied if we use `slogdet` as well?

2024-08-18 12:27 UTC, tanish1729 commented on pytensor/tensor/rewriting/linalg.py
> +@node_rewriter([det])
for logdet, the lod (prod) eventually becomes a summation which is different from what only det does. should it be working for logdet?

2024-08-18 12:30 UTC, jessegrabowski commented on pytensor/tensor/rewriting/linalg.py
> +@node_rewriter([det])
I think it would make sense. All of the initial checking logic will be shared, then you can check which op you have and return either sum or prod

2024-08-18 17:44 UTC, tanish1729 commented on pytensor/tensor/rewriting/linalg.py
> +@node_rewriter([det])
i have added it for slogdet but as a separate rewrite

2024-08-30 17:47 UTC, ricardoV94 commented on pytensor/tensor/rewriting/linalg.py
> +    return [prod(det_sub_matrices)]
I would do nothing. It's valid to have zeros in a product and we really restrict ourselves if we ever avoid prod because of JAX

2024-10-08 12:30 UTC, jessegrabowski approved these changes

2024-10-08 12:31 UTC, merged